# Generated by Django 5.1.4 on 2025-11-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(blank=True, default='Undefined Description'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='location',
            field=models.CharField(blank=True, default='Undefined Location', max_length=60),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(blank=True, default='Undefined Name', max_length=60),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='Undefined Phone Number', max_length=40),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='name',
            field=models.CharField(blank=True, default='Undefined Name', max_length=60),
        ),
    ]
