# Generated by Django 5.1.4 on 2025-11-24 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritecomplaintposts',
            name='complaint_post',
        ),
        migrations.RemoveField(
            model_name='favoritecomplaintposts',
            name='user',
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Undefined', max_length=60)),
                ('title', models.TextField(default='Undefined')),
                ('foreign_int', models.IntegerField()),
                ('object_type', models.PositiveSmallIntegerField(choices=[(0, 'user'), (1, 'complaint')])),
                ('company_profile_image_url', models.CharField(default='Undefined', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FavoriteCompanies',
        ),
        migrations.DeleteModel(
            name='FavoriteComplaintPosts',
        ),
    ]
